//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace EasyShopManagement.EntityFramework
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DueManagementEntity : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DueManagementEntity object using the connection string found in the 'DueManagementEntity' section of the application configuration file.
        /// </summary>
        public DueManagementEntity() : base("name=DueManagementEntity", "DueManagementEntity")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DueManagementEntity object.
        /// </summary>
        public DueManagementEntity(string connectionString) : base(connectionString, "DueManagementEntity")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DueManagementEntity object.
        /// </summary>
        public DueManagementEntity(EntityConnection connection) : base(connection, "DueManagementEntity")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CustomerInformation> CustomerInformations
        {
            get
            {
                if ((_CustomerInformations == null))
                {
                    _CustomerInformations = base.CreateObjectSet<CustomerInformation>("CustomerInformations");
                }
                return _CustomerInformations;
            }
        }
        private ObjectSet<CustomerInformation> _CustomerInformations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PaymentHistory> PaymentHistories
        {
            get
            {
                if ((_PaymentHistories == null))
                {
                    _PaymentHistories = base.CreateObjectSet<PaymentHistory>("PaymentHistories");
                }
                return _PaymentHistories;
            }
        }
        private ObjectSet<PaymentHistory> _PaymentHistories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ProductInformation> ProductInformations
        {
            get
            {
                if ((_ProductInformations == null))
                {
                    _ProductInformations = base.CreateObjectSet<ProductInformation>("ProductInformations");
                }
                return _ProductInformations;
            }
        }
        private ObjectSet<ProductInformation> _ProductInformations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ProductSaleHistory> ProductSaleHistories
        {
            get
            {
                if ((_ProductSaleHistories == null))
                {
                    _ProductSaleHistories = base.CreateObjectSet<ProductSaleHistory>("ProductSaleHistories");
                }
                return _ProductSaleHistories;
            }
        }
        private ObjectSet<ProductSaleHistory> _ProductSaleHistories;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CustomerInformations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCustomerInformations(CustomerInformation customerInformation)
        {
            base.AddObject("CustomerInformations", customerInformation);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PaymentHistories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPaymentHistories(PaymentHistory paymentHistory)
        {
            base.AddObject("PaymentHistories", paymentHistory);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProductInformations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProductInformations(ProductInformation productInformation)
        {
            base.AddObject("ProductInformations", productInformation);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProductSaleHistories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProductSaleHistories(ProductSaleHistory productSaleHistory)
        {
            base.AddObject("ProductSaleHistories", productSaleHistory);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DueManagementSystemDatabaseModel", Name="CustomerInformation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CustomerInformation : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CustomerInformation object.
        /// </summary>
        /// <param name="autoInc">Initial value of the AutoInc property.</param>
        /// <param name="customerName">Initial value of the CustomerName property.</param>
        /// <param name="dueAmount">Initial value of the DueAmount property.</param>
        /// <param name="createDate">Initial value of the CreateDate property.</param>
        public static CustomerInformation CreateCustomerInformation(global::System.Int64 autoInc, global::System.String customerName, global::System.Decimal dueAmount, global::System.DateTime createDate)
        {
            CustomerInformation customerInformation = new CustomerInformation();
            customerInformation.AutoInc = autoInc;
            customerInformation.CustomerName = customerName;
            customerInformation.DueAmount = dueAmount;
            customerInformation.CreateDate = createDate;
            return customerInformation;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 AutoInc
        {
            get
            {
                return _AutoInc;
            }
            set
            {
                if (_AutoInc != value)
                {
                    OnAutoIncChanging(value);
                    ReportPropertyChanging("AutoInc");
                    _AutoInc = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AutoInc");
                    OnAutoIncChanged();
                }
            }
        }
        private global::System.Int64 _AutoInc;
        partial void OnAutoIncChanging(global::System.Int64 value);
        partial void OnAutoIncChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CustomerName
        {
            get
            {
                return _CustomerName;
            }
            set
            {
                OnCustomerNameChanging(value);
                ReportPropertyChanging("CustomerName");
                _CustomerName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CustomerName");
                OnCustomerNameChanged();
            }
        }
        private global::System.String _CustomerName;
        partial void OnCustomerNameChanging(global::System.String value);
        partial void OnCustomerNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Mobile
        {
            get
            {
                return _Mobile;
            }
            set
            {
                OnMobileChanging(value);
                ReportPropertyChanging("Mobile");
                _Mobile = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Mobile");
                OnMobileChanged();
            }
        }
        private global::System.String _Mobile;
        partial void OnMobileChanging(global::System.String value);
        partial void OnMobileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ShopName
        {
            get
            {
                return _ShopName;
            }
            set
            {
                OnShopNameChanging(value);
                ReportPropertyChanging("ShopName");
                _ShopName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ShopName");
                OnShopNameChanged();
            }
        }
        private global::System.String _ShopName;
        partial void OnShopNameChanging(global::System.String value);
        partial void OnShopNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal DueAmount
        {
            get
            {
                return _DueAmount;
            }
            set
            {
                OnDueAmountChanging(value);
                ReportPropertyChanging("DueAmount");
                _DueAmount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DueAmount");
                OnDueAmountChanged();
            }
        }
        private global::System.Decimal _DueAmount;
        partial void OnDueAmountChanging(global::System.Decimal value);
        partial void OnDueAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Remark
        {
            get
            {
                return _Remark;
            }
            set
            {
                OnRemarkChanging(value);
                ReportPropertyChanging("Remark");
                _Remark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Remark");
                OnRemarkChanged();
            }
        }
        private global::System.String _Remark;
        partial void OnRemarkChanging(global::System.String value);
        partial void OnRemarkChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DueManagementSystemDatabaseModel", Name="PaymentHistory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PaymentHistory : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PaymentHistory object.
        /// </summary>
        /// <param name="autoInc">Initial value of the AutoInc property.</param>
        /// <param name="customerName">Initial value of the CustomerName property.</param>
        /// <param name="paymentDate">Initial value of the PaymentDate property.</param>
        /// <param name="amount">Initial value of the Amount property.</param>
        /// <param name="customerID">Initial value of the CustomerID property.</param>
        public static PaymentHistory CreatePaymentHistory(global::System.Int64 autoInc, global::System.String customerName, global::System.DateTime paymentDate, global::System.Decimal amount, global::System.Int64 customerID)
        {
            PaymentHistory paymentHistory = new PaymentHistory();
            paymentHistory.AutoInc = autoInc;
            paymentHistory.CustomerName = customerName;
            paymentHistory.PaymentDate = paymentDate;
            paymentHistory.Amount = amount;
            paymentHistory.CustomerID = customerID;
            return paymentHistory;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 AutoInc
        {
            get
            {
                return _AutoInc;
            }
            set
            {
                if (_AutoInc != value)
                {
                    OnAutoIncChanging(value);
                    ReportPropertyChanging("AutoInc");
                    _AutoInc = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AutoInc");
                    OnAutoIncChanged();
                }
            }
        }
        private global::System.Int64 _AutoInc;
        partial void OnAutoIncChanging(global::System.Int64 value);
        partial void OnAutoIncChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CustomerName
        {
            get
            {
                return _CustomerName;
            }
            set
            {
                OnCustomerNameChanging(value);
                ReportPropertyChanging("CustomerName");
                _CustomerName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CustomerName");
                OnCustomerNameChanged();
            }
        }
        private global::System.String _CustomerName;
        partial void OnCustomerNameChanging(global::System.String value);
        partial void OnCustomerNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime PaymentDate
        {
            get
            {
                return _PaymentDate;
            }
            set
            {
                OnPaymentDateChanging(value);
                ReportPropertyChanging("PaymentDate");
                _PaymentDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PaymentDate");
                OnPaymentDateChanged();
            }
        }
        private global::System.DateTime _PaymentDate;
        partial void OnPaymentDateChanging(global::System.DateTime value);
        partial void OnPaymentDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                OnAmountChanging(value);
                ReportPropertyChanging("Amount");
                _Amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Amount");
                OnAmountChanged();
            }
        }
        private global::System.Decimal _Amount;
        partial void OnAmountChanging(global::System.Decimal value);
        partial void OnAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 CustomerID
        {
            get
            {
                return _CustomerID;
            }
            set
            {
                OnCustomerIDChanging(value);
                ReportPropertyChanging("CustomerID");
                _CustomerID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CustomerID");
                OnCustomerIDChanged();
            }
        }
        private global::System.Int64 _CustomerID;
        partial void OnCustomerIDChanging(global::System.Int64 value);
        partial void OnCustomerIDChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DueManagementSystemDatabaseModel", Name="ProductInformation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProductInformation : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProductInformation object.
        /// </summary>
        /// <param name="autoInc">Initial value of the AutoInc property.</param>
        /// <param name="productName">Initial value of the ProductName property.</param>
        /// <param name="rate">Initial value of the Rate property.</param>
        public static ProductInformation CreateProductInformation(global::System.Int64 autoInc, global::System.String productName, global::System.Decimal rate)
        {
            ProductInformation productInformation = new ProductInformation();
            productInformation.AutoInc = autoInc;
            productInformation.ProductName = productName;
            productInformation.Rate = rate;
            return productInformation;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 AutoInc
        {
            get
            {
                return _AutoInc;
            }
            set
            {
                if (_AutoInc != value)
                {
                    OnAutoIncChanging(value);
                    ReportPropertyChanging("AutoInc");
                    _AutoInc = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AutoInc");
                    OnAutoIncChanged();
                }
            }
        }
        private global::System.Int64 _AutoInc;
        partial void OnAutoIncChanging(global::System.Int64 value);
        partial void OnAutoIncChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProductName
        {
            get
            {
                return _ProductName;
            }
            set
            {
                OnProductNameChanging(value);
                ReportPropertyChanging("ProductName");
                _ProductName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ProductName");
                OnProductNameChanged();
            }
        }
        private global::System.String _ProductName;
        partial void OnProductNameChanging(global::System.String value);
        partial void OnProductNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Rate
        {
            get
            {
                return _Rate;
            }
            set
            {
                OnRateChanging(value);
                ReportPropertyChanging("Rate");
                _Rate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Rate");
                OnRateChanged();
            }
        }
        private global::System.Decimal _Rate;
        partial void OnRateChanging(global::System.Decimal value);
        partial void OnRateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DueManagementSystemDatabaseModel", Name="ProductSaleHistory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProductSaleHistory : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProductSaleHistory object.
        /// </summary>
        /// <param name="autoInc">Initial value of the AutoInc property.</param>
        /// <param name="saleDate">Initial value of the SaleDate property.</param>
        /// <param name="productName">Initial value of the ProductName property.</param>
        /// <param name="rate">Initial value of the Rate property.</param>
        /// <param name="quantity">Initial value of the Quantity property.</param>
        /// <param name="customerID">Initial value of the CustomerID property.</param>
        public static ProductSaleHistory CreateProductSaleHistory(global::System.Int64 autoInc, global::System.DateTime saleDate, global::System.String productName, global::System.Decimal rate, global::System.Decimal quantity, global::System.Int64 customerID)
        {
            ProductSaleHistory productSaleHistory = new ProductSaleHistory();
            productSaleHistory.AutoInc = autoInc;
            productSaleHistory.SaleDate = saleDate;
            productSaleHistory.ProductName = productName;
            productSaleHistory.Rate = rate;
            productSaleHistory.Quantity = quantity;
            productSaleHistory.CustomerID = customerID;
            return productSaleHistory;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 AutoInc
        {
            get
            {
                return _AutoInc;
            }
            set
            {
                if (_AutoInc != value)
                {
                    OnAutoIncChanging(value);
                    ReportPropertyChanging("AutoInc");
                    _AutoInc = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AutoInc");
                    OnAutoIncChanged();
                }
            }
        }
        private global::System.Int64 _AutoInc;
        partial void OnAutoIncChanging(global::System.Int64 value);
        partial void OnAutoIncChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime SaleDate
        {
            get
            {
                return _SaleDate;
            }
            set
            {
                OnSaleDateChanging(value);
                ReportPropertyChanging("SaleDate");
                _SaleDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SaleDate");
                OnSaleDateChanged();
            }
        }
        private global::System.DateTime _SaleDate;
        partial void OnSaleDateChanging(global::System.DateTime value);
        partial void OnSaleDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProductName
        {
            get
            {
                return _ProductName;
            }
            set
            {
                OnProductNameChanging(value);
                ReportPropertyChanging("ProductName");
                _ProductName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ProductName");
                OnProductNameChanged();
            }
        }
        private global::System.String _ProductName;
        partial void OnProductNameChanging(global::System.String value);
        partial void OnProductNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustomerName
        {
            get
            {
                return _CustomerName;
            }
            set
            {
                OnCustomerNameChanging(value);
                ReportPropertyChanging("CustomerName");
                _CustomerName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CustomerName");
                OnCustomerNameChanged();
            }
        }
        private global::System.String _CustomerName;
        partial void OnCustomerNameChanging(global::System.String value);
        partial void OnCustomerNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Rate
        {
            get
            {
                return _Rate;
            }
            set
            {
                OnRateChanging(value);
                ReportPropertyChanging("Rate");
                _Rate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Rate");
                OnRateChanged();
            }
        }
        private global::System.Decimal _Rate;
        partial void OnRateChanging(global::System.Decimal value);
        partial void OnRateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Quantity
        {
            get
            {
                return _Quantity;
            }
            set
            {
                OnQuantityChanging(value);
                ReportPropertyChanging("Quantity");
                _Quantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Quantity");
                OnQuantityChanged();
            }
        }
        private global::System.Decimal _Quantity;
        partial void OnQuantityChanging(global::System.Decimal value);
        partial void OnQuantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 CustomerID
        {
            get
            {
                return _CustomerID;
            }
            set
            {
                OnCustomerIDChanging(value);
                ReportPropertyChanging("CustomerID");
                _CustomerID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CustomerID");
                OnCustomerIDChanged();
            }
        }
        private global::System.Int64 _CustomerID;
        partial void OnCustomerIDChanging(global::System.Int64 value);
        partial void OnCustomerIDChanged();

        #endregion
    
    }

    #endregion
    
}
